# Generated by Django 5.2.9 on 2026-01-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('eligibility', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('process', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('reg_no', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=100)),
                ('btech_percent', models.FloatField()),
                ('inter_percent', models.FloatField()),
                ('ssc_percent', models.FloatField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_image', models.ImageField(upload_to='profile_pics/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='frontend.drive')),
            ],
        ),
    ]
