# Generated by Django 5.2.9 on 2026-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_drive_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('student_photo', models.ImageField(upload_to='student_photos/')),
            ],
        ),
    ]
