# Generated by Django 5.2.9 on 2026-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_selectedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedstudent',
            name='student_photo',
            field=models.ImageField(upload_to='selected_students/'),
        ),
    ]
