# Generated by Django 5.2.9 on 2026-01-06 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_selectedstudent_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='eligible_branches',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='job_role',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='last_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
