# Generated by Django 5.2.9 on 2026-01-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_drive_eligible_branches_drive_job_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='eligible_branches',
            new_name='Eligible_Branches',
        ),
    ]
