# Generated by Django 5.2.9 on 2026-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_eligible_branches_drive_eligible_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='Eligible_Branches',
        ),
        migrations.AddField(
            model_name='drive',
            name='Eligible_branches',
            field=models.CharField(default='CSE', max_length=255),
            preserve_default=False,
        ),
    ]
