# Generated by Django 5.2.9 on 2026-01-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_drive_eligible_branches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='Eligible_branches',
            new_name='eligible_branches',
        ),
    ]
