# Generated by Django 5.2.9 on 2026-01-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_eligible_branches_drive_eligible_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='job_role',
            field=models.CharField(max_length=100),
        ),
    ]
